### PR TITLE
Python & Django upgrade

### PR DESCRIPTION
**Pull request by SunnyR**
https://sdelements.atlassian.net/browse/DEVOP-6780

### CODE REVIEW

**Review by RouganStriker — COMMENTED** [review]
Did we need to drop the crisp-form code? I know it is not a feature we use but it would be nice to minimize the changes we make to the repo.

**Comment by SunnyR** [comment]
> Did we need to drop the crisp-form code? I know it is not a feature we use but it would be nice to minimize the changes we make to the repo.

The crisp code fails a bunch of tests around rendering bootstrap3 html. The upstream repo has those failing tests as well in 1.0.0.dev1, so since we don't use it I dropped it. Another reason was to reduce the dependencies this project would have.

**Comment by RouganStriker** [comment]
> > Did we need to drop the crisp-form code? I know it is not a feature we use but it would be nice to minimize the changes we make to the repo.
> 
> The crisp code fails a bunch of tests around rendering bootstrap3 html. The upstream repo has those failing tests as well in 1.0.0.dev1, so since we don't use it I dropped it. Another reason was to reduce the dependencies this project would have.

Gotcha, if its too much effort let's skip it. Could we just make a note on the readme that we dropped the crispy form in our fork?

**Comment by SunnyR** [comment]
> > > Did we need to drop the crisp-form code? I know it is not a feature we use but it would be nice to minimize the changes we make to the repo.
> > 
> > 
> > The crisp code fails a bunch of tests around rendering bootstrap3 html. The upstream repo has those failing tests as well in 1.0.0.dev1, so since we don't use it I dropped it. Another reason was to reduce the dependencies this project would have.
> 
> Gotcha, if its too much effort let's skip it. Could we just make a note on the readme that we dropped the crispy form in our fork?

Updated the readme to include changes made in the fork.

**Review by RouganStriker — APPROVED** [review]
+1 changes look good to me

**Pull request merged**
